# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
mod_version=1.12.2-1.4-pre11

# HTTP 代理配置
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7890

# HTTPS 代理配置 (通常和 HTTP 相同)
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7890